trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Install Node.js v22.8.0
- task: UseNode@1
  inputs:
    versionSpec: '22.8.0'

# Install dependencies
- script: npm install
  displayName: 'Install dependencies'

# Run the app using npm start
- script: npm start
  displayName: 'Start the application'
