trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Install Node.js v22.8.0 using UseNode@1 task
- task: UseNode@1
  inputs:
    versionSpec: '22.8.0'  # Specify the exact Node.js version you need
  displayName: 'Install Node.js v22.8.0'

# Check Node.js version to confirm the correct version is installed
- script: |
    node --version
  displayName: 'Check Node.js version'

# Navigate to the /server folder and install dependencies
- script: |
    cd server
    npm install
  displayName: 'Install dependencies in /server'

# Start the server (optional, if part of your pipeline)
- script: |
    cd server
    npm start
  displayName: 'Start the server in /server'
