trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Install Node.js and npm, then install dependencies in /server
- script: |
    sudo apt update
    sudo apt install -y nodejs
    sudo apt install -y npm
    cd server
    npm install
    ls
    node --version
  displayName: 'Install dependencies in /server'
