trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Install Node.js v22.8.0
- task: UseNode@1
  inputs:
    versionSpec: '22.8.0'
  
- script: |
    cd server
    npm install
    ls
  displayName: 'Install dependencies in /server'
